### ISSUE TITLE
Shouldn't the icon be SVG?

### ISSUE THREAD

**Issue by KOLANICH** [claustromaniac/poop#1]
And I recommend to rewrite the history. Storing binary files in git is not good. If you strictly have to, use git-lfs.

**Comment by claustromaniac** [comment]
I see your point. Thanks :+1:

**Comment by claustromaniac** [comment]
3924324

**Comment by KOLANICH** [comment]
Thanks. Is the `pile of poo` on the pic traced from some font? Do we really need it look the same on every machine? I mean why not to just put a `💩` character into SVG sized to fill all the square?

**Comment by claustromaniac** [comment]
> to fill all the square

That's easier said than done. As you implied, that character won't look the same on every machine, which means the icon will get cropped for some people. 

Besides, I've seen other extensions using that as an icon already (it's a damn popular emoji). I made the current icon myself, which makes it somewhat unique, and in turn makes the extension look less generic (I guess?). In other words: this is not just *any* :hankey:, this is THE :hankey:!!

Jokes aside, I'm not too particular about the name and icon, but I guess those are the most subjective aspects (see [here](https://github.com/ghacksuserjs/ghacks-user.js/issues/509#issuecomment-443431397)). Suggestions and/or pull requests are welcome.
