### ISSUE TITLE
dealing with preflight requests for GET requests

### ISSUE THREAD

**Issue by claustromaniac** [claustromaniac/poop#12]
@crssi [said](https://github.com/claustromaniac/poop/issues/11#issuecomment-449932638):

> something is telling me that `OPTIONS` request where ACRM = GET, should also be altered somehow.

All things considered, I definitely agree with you on that! :+1: :heart:
This was a total oversight on my part because I never stopped to consider doing anything about preflight requests in the first place. Be sure to let me know if you notice anything else worth looking into (or if you think I'm missing something else). Thanks! :smile_cat: 

- [x] process `OPTIONS` requests when `Access-Control-Request-Method: GET`
- [x] update documentation

**Comment by crssi** [comment]
Looks like you have nailed it in `1.3.0b`.
Great job as usual. :smile_cat: 

Thank you and cheers

**Comment by claustromaniac** [comment]
`1.3.0` is up! Thank you again :kissing_cat: that was a good catch :+1:
