### ISSUE TITLE
UX shit

### ISSUE THREAD

**Issue by claustromaniac** [claustromaniac/poop#2]
Some stuff for my ever-growing to-do list...

- [x] add a whitelist
    - [x] an alternative would be to add an accessible switch for toggling the extension on and off, for the (so far hypothetical) cases when shit breaks and there is nothing else to do about it. 
- [x] add toolbar and/or urlbar icons
  - [x] maybe with a badge counter. Very low priority.
- [x] change the icon when the master switch is off
  - the badge changes instead.
- [x] remember the state of the `<details>` elements in the options page
- [x] reword/rename stuff... particular areas I'm still not convinced about:
  - [x] short description
    - still not convinced
  - ~~stats section of the popup - I don't know what to put here.~~
  - [x] `Strict resource types`? Maybe `Type filters` or something of the sort instead
- [x] reconsider internationalizing the extension
  - ~~seriously reconsider it~~
- [x] ~~update~~ write documentation. Seriously.

**Comment by KOLANICH** [comment]
How about merging it into μmatrix?

**Comment by claustromaniac** [comment]
Many people don't use uMatrix, but they still might want to use this extension. Moreover, I can't spare the time to do that additional work myself (my plate is already overflowing). If gorhill is interested and someone is willing to do it, then by all means go ahead. Also, I'm not as experienced a coder as gorhill or others, and I admit I'm not super considerate when it comes to making my code pretty/readable and such, so they wouldn't want to include this as-is anyway. 

Even with these new additions, this is still pretty damn minimalist compared to extensions like uBO and uMatrix, etc. Heck, this doesn't even make use of the localization APIs, and it only uses Firefox-specific APIs (it would take some rework to get it working in other browsers).

**Comment by crssi** [comment]
Could you make UI settings page flat (without drop down), like it was some versions ago?
I find flat more friendly, since I can see all the settings right away not needing to "drill" from one to another.

Cheers

**Comment by claustromaniac** [comment]
the state of those elements should be remembered now in [the current release candidate](https://github.com/claustromaniac/poop/releases/tag/1.0.0b7), so we don't need to open them every time anymore.
