### ISSUE TITLE
verify necessity

### ISSUE THREAD

**Issue by atomGit** [claustromaniac/poop#30]
hi claustro! since i'm not super techie i just wanted to re-verify that poop is still useful with FF v84 and beyond considering that i'm using the arkenfox js with FPI and RFP enabled - thanks!

**Comment by crssi** [comment]
I know you have asked @claustromaniac and not others.
But if my opinion is worth, then: **For sure it is!**

Cheers

**Comment by atomGit** [comment]
...and i'm back again with the same Q: given FF v96, arkenfox with dFPI/net partitioning, do we still POOP?

**Comment by crssi** [comment]
@atomGit what is your opinion on referers?
Should referers be sanitized or not?

**Comment by atomGit** [comment]
yes, i think so - arkenfox js does this by default (no ext. needed) - see section 1600

**Comment by crssi** [comment]
So, similarly as the referers leak there is a leak over CORS.

**Comment by crssi** [comment]
@atomGit was the answer on arkenfox thread sufficient? Can this one be closed?
