### ISSUE TITLE
improving overrides feature

### ISSUE THREAD

**Issue by ghost** [claustromaniac/poop#4]
Hi @claustromaniac 

I'm enjoying POOP 1.0.0b2 / Firefox 63.0.3 (x64) / Windows 7 (x64).

I'll take the example which initiates this very comment:

_Google Web search_ supports relaxed and even aggressive POOP mode (in fact nothing is even blocked) but _Google Maps's satellite view_ will fail even with POOP's relaxed mode; hence, I have to whitelist `www.google.com` and that works perfectly of course.

I've tried to manually replace `www.google.com` by `www.google.com/maps` in POOP's Overrides but unsuccessfully : doing so leads to `www.google.com` not considered at all.

Is it possible therefor to consider the enhancement which would allow the user to differenciate a domain from a sub-domain when whitelisting a site?

Thanks!

**Comment by claustromaniac** [comment]
Hi Stan, 

I couldn't reproduce your issue with google maps' satellite view, but I still think that improving the override feature is worthwhile. When I can, I think I will implement wildcard and regex patterns, among other things. I also have in mind some changes to make sure such improvements don't affect performance significantly.

Thanks for your feedback :+1:

**Comment by ghost** [comment]
> I couldn't reproduce your issue with google maps' satellite view,

I've just tested _Google Maps satellite view_ again, doesn't display with _relaxed mode_ and _Strict resource types_ left at default (but does of course with `www.google.com` whitelisted). Really odd that you don't encounter. I'm perplex.

Anyway that is an example which remains valid as for what it means.

> When I can, I think I will implement wildcard and regex patterns, among other things

After all POOP is still in beta stage but as it is it undoubtedly runs nicely and the whitelist is functional.
Always a pleasure to notice the altered requests.

Staying tuned of course.
