### ISSUE TITLE
overlapping text on pop-up

### ISSUE THREAD

**Issue by atomGit** [claustromaniac/poop#8]
https://upload.disroot.org/r/nXGp6M0A#QnK2yelmdgVZmTHtR24fmRt27rGgGshOHf6FawmX+UI=

note that i have `layout.css.devPixelsPerPx` @ 1.3 and font sizes set fairly large-ish to make stuff readable on a 17" 1080p display

**Comment by claustromaniac** [comment]
Please try [`1.1.0b`](https://github.com/claustromaniac/poop/releases/tag/1.1.0b) when you can, and let me know how it looks on your end.

**Comment by atomGit** [comment]
ooooo it looks perdy :)

yeah, works fine - oh wow, it even [stretches](https://llanfairpwllgwyngyllgogerychwyrndrobwllllantysiliogogogoch.co.uk/)

**Comment by claustromaniac** [comment]
Thank you sir! :cat:
