### ISSUE TITLE
enhance: a link to settings page on toolbar pop-up...

### ISSUE THREAD

**Issue by atomGit** [claustromaniac/poop#9]
...might be handy?

**Comment by claustromaniac** [comment]
I thought about it, but there is already the `Manage Extension` option in the context menu when you right-click the toolbar icon. I don't remember in which version of FF that was added... 62? 63? gotta check that first.

**Comment by claustromaniac** [comment]
It seems it was added in FF62. I guess adding this would be of help at least to users of FF57-61. It also means less clicks for users of 62+ when they already opened the popup.

**Comment by atomGit** [comment]
oops - yup - forgot about that - i went from 57 i think it was to 60 something, so it's new to me - i'd forget about this request if i were you - it was trivial

**Comment by claustromaniac** [comment]
It was also trivial to implement, so no worries.
